-- =====================================================================
-- MayChat 0.39.0 — "Nhìn hình đoán chữ" and renaming a farm for gold
--  * Đoán chữ: pictures (emoji) -> a Vietnamese word, typed with letter
--    tiles (no accents). 10 puzzles a day; a right answer gives 10 gold and
--    1 time in 10 a building material (gỗ, ngói or gạch, at random).
--    Hints cost gold: open 1 letter 20, take away the extra letters 30,
--    skip the puzzle 50 (a skipped puzzle counts in the 10 of the day).
--    The answers stay on the server: the phone never sees them.
--  * Renaming a farm now costs 10,000 gold (changing the farmer is free).
-- Run once in Supabase → SQL Editor (after migration 38). Safe to run again.
-- To add puzzles later: insert into public.farm_words (level, pics, answer, shown)
--   values (2, '🐄 🥛', 'SUA BO', 'Sữa bò');  -- answer: capitals, no accents
-- New puzzles come after the ones a player has done (order of id).
-- =====================================================================

-- 1. The puzzles (nobody reads this table directly)
create table if not exists public.farm_words (
    id      int generated by default as identity primary key,
    level   int  not null default 1 check (level between 1 and 3),
    pics    text not null,
    answer  text not null check (answer ~ '^[A-Z]+( [A-Z]+)*$'),
    shown   text not null,
    active  boolean not null default true
);
alter table public.farm_words enable row level security;
revoke all on public.farm_words from anon, authenticated;

insert into public.farm_words (id, level, pics, answer, shown) values
    (1, 1, '🐄 🥛', 'SUA BO', 'Sữa bò'),
    (2, 1, '🐔 🥚', 'TRUNG GA', 'Trứng gà'),
    (3, 1, '🍜 🐄', 'PHO BO', 'Phở bò'),
    (4, 1, '🍚 🐔', 'COM GA', 'Cơm gà'),
    (5, 1, '🥖 🥩', 'BANH MI THIT', 'Bánh mì thịt'),
    (6, 1, '☕ 🥛', 'CA PHE SUA', 'Cà phê sữa'),
    (7, 1, '🍵 🧊', 'TRA DA', 'Trà đá'),
    (8, 1, '🍉', 'DUA HAU', 'Dưa hấu'),
    (9, 1, '🥥 🌴', 'CAY DUA', 'Cây dừa'),
    (10, 1, '🍌 🌳', 'CAY CHUOI', 'Cây chuối'),
    (11, 1, '🥕', 'CA ROT', 'Cà rốt'),
    (12, 1, '🍅', 'CA CHUA', 'Cà chua'),
    (13, 1, '🍆', 'CA TIM', 'Cà tím'),
    (14, 1, '🥔', 'KHOAI TAY', 'Khoai tây'),
    (15, 1, '🍠 🔥', 'KHOAI NUONG', 'Khoai nướng'),
    (16, 1, '🥭', 'XOAI', 'Xoài'),
    (17, 1, '🌻', 'HOA HUONG DUONG', 'Hoa hướng dương'),
    (18, 1, '🌸 🍑', 'HOA DAO', 'Hoa đào'),
    (19, 1, '🍀', 'CO BON LA', 'Cỏ bốn lá'),
    (20, 1, '🌈', 'CAU VONG', 'Cầu vồng'),
    (21, 1, '⛈️ ⚡', 'SAM SET', 'Sấm sét'),
    (22, 1, '🌋', 'NUI LUA', 'Núi lửa'),
    (23, 1, '🌊 🏖️', 'BAI BIEN', 'Bãi biển'),
    (24, 1, '⭐ 🌊', 'SAO BIEN', 'Sao biển'),
    (25, 1, '🐬', 'CA HEO', 'Cá heo'),
    (26, 1, '🐋', 'CA VOI', 'Cá voi'),
    (27, 1, '🦈', 'CA MAP', 'Cá mập'),
    (28, 1, '🦒', 'HUOU CAO CO', 'Hươu cao cổ'),
    (29, 1, '🦓', 'NGUA VAN', 'Ngựa vằn'),
    (30, 1, '🐌', 'CON OC', 'Con ốc'),
    (31, 1, '🦀', 'CON CUA', 'Con cua'),
    (32, 1, '🐍', 'CON RAN', 'Con rắn'),
    (33, 1, '🦔', 'CON NHIM', 'Con nhím'),
    (34, 1, '🐿️', 'CON SOC', 'Con sóc'),
    (35, 1, '🦚', 'CON CONG', 'Con công'),
    (36, 1, '🦜', 'CON VET', 'Con vẹt'),
    (37, 1, '🐝 🍯', 'MAT ONG', 'Mật ong'),
    (38, 1, '🕷️ 🕸️', 'MANG NHEN', 'Mạng nhện'),
    (39, 1, '🚲', 'XE DAP', 'Xe đạp'),
    (40, 1, '🏍️', 'XE MAY', 'Xe máy'),
    (41, 1, '✈️', 'MAY BAY', 'Máy bay'),
    (42, 1, '🚂', 'TAU HOA', 'Tàu hỏa'),
    (43, 1, '🚢', 'TAU THUY', 'Tàu thủy'),
    (44, 1, '🚒', 'XE CUU HOA', 'Xe cứu hỏa'),
    (45, 1, '🚑', 'XE CUU THUONG', 'Xe cứu thương'),
    (46, 1, '📱', 'DIEN THOAI', 'Điện thoại'),
    (47, 1, '📺', 'TI VI', 'Ti vi'),
    (48, 1, '💡', 'BONG DEN', 'Bóng đèn'),
    (49, 1, '🧲', 'NAM CHAM', 'Nam châm'),
    (50, 1, '🧭', 'LA BAN', 'La bàn'),
    (51, 1, '🗺️', 'BAN DO', 'Bản đồ'),
    (52, 1, '✏️', 'BUT CHI', 'Bút chì'),
    (53, 1, '🔑', 'CHIA KHOA', 'Chìa khóa'),
    (54, 1, '🧹', 'CAI CHOI', 'Cái chổi'),
    (55, 1, '🏮', 'DEN LONG', 'Đèn lồng'),
    (56, 1, '🧧', 'LI XI', 'Lì xì'),
    (57, 2, '🎂 🕯️ 🎉', 'SINH NHAT', 'Sinh nhật'),
    (58, 2, '💍 👰 🤵', 'DAM CUOI', 'Đám cưới'),
    (59, 2, '⚽ 🥅', 'BONG DA', 'Bóng đá'),
    (60, 2, '🏸', 'CAU LONG', 'Cầu lông'),
    (61, 2, '🏊', 'BOI LOI', 'Bơi lội'),
    (62, 2, '🎤 🎶', 'CA HAT', 'Ca hát'),
    (63, 2, '🏫 📚', 'TRUONG HOC', 'Trường học'),
    (64, 2, '🏥', 'BENH VIEN', 'Bệnh viện'),
    (65, 2, '👩‍⚕️', 'BAC SI', 'Bác sĩ'),
    (66, 2, '👨‍🍳', 'DAU BEP', 'Đầu bếp'),
    (67, 2, '👨‍🌾', 'NONG DAN', 'Nông dân'),
    (68, 2, '👨‍🏫', 'THAY GIAO', 'Thầy giáo'),
    (69, 2, '🎓', 'TOT NGHIEP', 'Tốt nghiệp'),
    (70, 2, '🌧️ 🧥', 'AO MUA', 'Áo mưa'),
    (71, 2, '🌕 🥮', 'TRUNG THU', 'Trung thu'),
    (72, 2, '🌟 🏮', 'DEN ONG SAO', 'Đèn ông sao'),
    (73, 2, '🦁 🥁', 'MUA LAN', 'Múa lân'),
    (74, 2, '🎆 🧧 🌸', 'TET', 'Tết'),
    (75, 2, '🐷 💰', 'HEO DAT', 'Heo đất'),
    (76, 2, '🌾 🚜', 'GAT LUA', 'Gặt lúa'),
    (77, 2, '🍜 🐄 🏯', 'BUN BO HUE', 'Bún bò Huế'),
    (78, 2, '🍲 🍋', 'CANH CHUA', 'Canh chua'),
    (79, 2, '🍃 🍚 🐷', 'BANH CHUNG', 'Bánh chưng'),
    (80, 2, '🥟', 'BANH BAO', 'Bánh bao'),
    (81, 2, '⌛', 'DONG HO CAT', 'Đồng hồ cát'),
    (82, 2, '🍎 👸', 'BACH TUYET', 'Bạch Tuyết'),
    (83, 2, '🧜‍♀️', 'NANG TIEN CA', 'Nàng tiên cá'),
    (84, 2, '👠 🎃', 'CO BE LO LEM', 'Cô bé Lọ Lem'),
    (85, 2, '🐢 🐇', 'RUA VA THO', 'Rùa và thỏ'),
    (86, 2, '🦉', 'CU MEO', 'Cú mèo'),
    (87, 2, '🐟 ➡️ 🐉', 'CA CHEP HOA RONG', 'Cá chép hóa rồng'),
    (88, 2, '🍉 🏝️', 'MAI AN TIEM', 'Mai An Tiêm'),
    (89, 2, '🐉 🧚', 'CON RONG CHAU TIEN', 'Con Rồng cháu Tiên'),
    (90, 2, '⛰️ ⚔️ 🌊', 'SON TINH THUY TINH', 'Sơn Tinh Thủy Tinh'),
    (91, 2, '🐎 🔥 🎋', 'THANH GIONG', 'Thánh Gióng'),
    (92, 2, '🎋 💯', 'CAY TRE TRAM DOT', 'Cây tre trăm đốt'),
    (93, 2, '🐟 🐦 👠', 'TAM CAM', 'Tấm Cám'),
    (94, 2, '🦊 🐯', 'CAO MUON OAI HUM', 'Cáo mượn oai hùm'),
    (95, 3, '🍚 🥣 🦶 🍽️', 'AN CHAO DA BAT', 'Ăn cháo đá bát'),
    (96, 3, '🍎 🧠 👨‍🌾 🌳', 'AN QUA NHO KE TRONG CAY', 'Ăn quả nhớ kẻ trồng cây'),
    (97, 3, '🐸 🕳️', 'ECH NGOI DAY GIENG', 'Ếch ngồi đáy giếng'),
    (98, 3, '🎻 👂 🐃', 'DAN GAY TAI TRAU', 'Đàn gảy tai trâu'),
    (99, 3, '🦆 👂 ⛈️', 'NHU VIT NGHE SAM', 'Như vịt nghe sấm'),
    (100, 3, '🍄 🌧️', 'NHU NAM SAU MUA', 'Như nấm sau mưa'),
    (101, 3, '🧙‍♂️ 👀 🐘', 'THAY BOI XEM VOI', 'Thầy bói xem voi'),
    (102, 3, '💧 🔥', 'NUOC SOI LUA BONG', 'Nước sôi lửa bỏng'),
    (103, 3, '🐋 🐟', 'CA LON NUOT CA BE', 'Cá lớn nuốt cá bé'),
    (104, 3, '🥢 🥢 🥢 💪', 'BO DUA', 'Bó đũa'),
    (105, 3, '🌳 🌳 🌳 ⛰️', 'BA CAY CHUM LAI NEN HON NUI CAO', 'Ba cây chụm lại nên hòn núi cao'),
    (106, 3, '🐢 ⏳', 'CHAM NHU RUA', 'Chậm như rùa'),
    (107, 3, '🐘 💪', 'KHOE NHU VOI', 'Khỏe như voi'),
    (108, 3, '🐟 💧', 'NHU CA GAP NUOC', 'Như cá gặp nước'),
    (109, 3, '🐔 🐔 👩', 'GA CUNG MOT ME', 'Gà cùng một mẹ'),
    (110, 3, '⛵ 🌬️', 'THUAN BUOM XUOI GIO', 'Thuận buồm xuôi gió'),
    (111, 3, '🤐 🥇', 'IM LANG LA VANG', 'Im lặng là vàng'),
    (112, 3, '⏰ 💰', 'THOI GIAN LA VANG', 'Thời gian là vàng'),
    (113, 3, '🐶 ❌ 🐱', 'NHU CHO VOI MEO', 'Như chó với mèo'),
    (114, 3, '🏹 🎯 🎯', 'MOT MUI TEN TRUNG HAI DICH', 'Một mũi tên trúng hai đích'),
    (115, 3, '🥶 🧊', 'LANH NHU BANG', 'Lạnh như băng'),
    (116, 3, '🥵 🔥', 'NONG NHU LUA', 'Nóng như lửa')
on conflict (id) do nothing;
do $x$ begin perform setval(pg_get_serial_sequence('public.farm_words', 'id'), greatest((select max(id) from public.farm_words), 1)); end $x$;

-- 2. Where each player is
alter table public.farms add column if not exists word_last int     not null default 0;   -- id of the last puzzle done
alter table public.farms add column if not exists word_day  date;
alter table public.farms add column if not exists word_n    int     not null default 0;   -- puzzles done that day
alter table public.farms add column if not exists word_open int[]   not null default '{}'; -- letters opened by a hint
alter table public.farms add column if not exists word_cut  boolean not null default false; -- extra letters taken away

-- 3. The puzzle as the phone sees it: pictures, word lengths, letter tiles
create or replace function public.farm_word_view(f public.farms)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_today date := public.farm_today();
    v_n int := case when f.word_day = v_today then f.word_n else 0 end;
    w public.farm_words;
    v_ans text;
    v_len int;
    v_tiles text[] := '{}';
    v_abc text := 'ABCDEGHIKLMNOPQRSTUVXY';
    v_extra int;
    v_letters jsonb;
    v_open jsonb;
    i int;
begin
    select * into w from public.farm_words where active and id > f.word_last order by id limit 1;
    if not found then
        return jsonb_build_object('n', v_n, 'max', 10, 'finished', true);
    end if;
    v_ans := replace(w.answer, ' ', '');
    v_len := char_length(v_ans);
    -- the letters of the answer, then some extra letters (always the same for a puzzle)
    for i in 1 .. v_len loop v_tiles := v_tiles || substr(v_ans, i, 1); end loop;
    v_extra := greatest(4, 14 - v_len);
    for i in 1 .. v_extra loop
        v_tiles := v_tiles || substr(v_abc, 1 + ('x' || substr(md5(w.id || ':e:' || i), 1, 6))::bit(24)::int % char_length(v_abc), 1);
    end loop;
    select jsonb_agg(t.l order by md5(w.id || ':s:' || t.k)) into v_letters
      from unnest(v_tiles) with ordinality as t(l, k)
     where not f.word_cut or t.k <= v_len;
    select coalesce(jsonb_agg(jsonb_build_object('i', o, 'c', substr(v_ans, o + 1, 1)) order by o), '[]'::jsonb) into v_open
      from unnest(f.word_open) as o;
    return jsonb_build_object(
        'n', v_n, 'max', 10, 'finished', false,
        'id', w.id, 'level', w.level, 'pics', w.pics,
        'words', (select jsonb_agg(char_length(x) order by k) from unnest(string_to_array(w.answer, ' ')) with ordinality as s(x, k)),
        'letters', v_letters, 'open', v_open, 'cut', f.word_cut,
        'costs', jsonb_build_object('letter', 20, 'cut', 30, 'skip', 50)
    );
end;
$$;

-- 4. Opening the game
create or replace function public.farm_word_get()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_me uuid := auth.uid();
    f public.farms;
begin
    if v_me is null then raise exception 'not_authenticated'; end if;
    select * into f from public.farms where user_id = v_me;
    if not found then raise exception 'no_farm'; end if;
    return public.farm_state(f) || jsonb_build_object('word', public.farm_word_view(f));
end;
$$;

-- 5. An answer: all the letters of the tiles, in order (spaces not needed)
create or replace function public.farm_word_answer(p_letters text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_me uuid := auth.uid();
    v_today date := public.farm_today();
    f public.farms;
    w public.farm_words;
    v_n int;
    v_mat text;
begin
    if v_me is null then raise exception 'not_authenticated'; end if;
    select * into f from public.farms where user_id = v_me for update;
    if not found then raise exception 'no_farm'; end if;
    v_n := case when f.word_day = v_today then f.word_n else 0 end;
    if v_n >= 10 then raise exception 'word_day_done'; end if;
    select * into w from public.farm_words where active and id > f.word_last order by id limit 1;
    if not found then raise exception 'word_finished'; end if;

    if regexp_replace(upper(coalesce(p_letters, '')), '[^A-Z]', '', 'g') <> replace(w.answer, ' ', '') then
        return public.farm_state(f) || jsonb_build_object('word', public.farm_word_view(f), 'result', jsonb_build_object('ok', false));
    end if;

    -- right: 10 gold, and 1 time in 10 a material
    if random() < 0.1 then v_mat := (array['go', 'ngoi', 'gach'])[1 + floor(random() * 3)::int]; end if;
    f := public.farm_roll(f);
    f.week_gold := f.week_gold + 10;
    perform public.farm_save_counters(f);
    update public.farms
       set gold = gold + 10,
           mats = case when v_mat is null then mats else public.farm_mat_add(mats, v_mat, 1) end,
           word_last = w.id, word_day = v_today, word_n = v_n + 1, word_open = '{}', word_cut = false,
           updated_at = now()
     where user_id = v_me
    returning * into f;
    return public.farm_state(f) || jsonb_build_object(
        'word', public.farm_word_view(f),
        'result', jsonb_build_object('ok', true, 'shown', w.shown, 'gold', 10, 'mat', v_mat)
    );
end;
$$;

-- 6. Hints: 'letter' (20 gold), 'cut' (30), 'skip' (50)
create or replace function public.farm_word_hint(p_kind text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_me uuid := auth.uid();
    v_today date := public.farm_today();
    f public.farms;
    w public.farm_words;
    v_n int;
    v_cost int;
    v_len int;
    v_next int;
begin
    if v_me is null then raise exception 'not_authenticated'; end if;
    v_cost := case p_kind when 'letter' then 20 when 'cut' then 30 when 'skip' then 50 else null end;
    if v_cost is null then raise exception 'bad_hint'; end if;
    select * into f from public.farms where user_id = v_me for update;
    if not found then raise exception 'no_farm'; end if;
    v_n := case when f.word_day = v_today then f.word_n else 0 end;
    if v_n >= 10 then raise exception 'word_day_done'; end if;
    select * into w from public.farm_words where active and id > f.word_last order by id limit 1;
    if not found then raise exception 'word_finished'; end if;
    if f.gold < v_cost then raise exception 'not_enough_gold'; end if;
    v_len := char_length(replace(w.answer, ' ', ''));

    if p_kind = 'letter' then
        select min(i) into v_next from generate_series(0, v_len - 1) i where not (i = any(f.word_open));
        if v_next is null or cardinality(f.word_open) >= v_len - 1 then raise exception 'no_more_hint'; end if;
        update public.farms set gold = gold - v_cost, word_open = word_open || v_next, updated_at = now()
         where user_id = v_me returning * into f;
    elsif p_kind = 'cut' then
        if f.word_cut then raise exception 'no_more_hint'; end if;
        update public.farms set gold = gold - v_cost, word_cut = true, updated_at = now()
         where user_id = v_me returning * into f;
    else
        update public.farms
           set gold = gold - v_cost, word_last = w.id, word_day = v_today, word_n = v_n + 1,
               word_open = '{}', word_cut = false, updated_at = now()
         where user_id = v_me returning * into f;
        return public.farm_state(f) || jsonb_build_object('word', public.farm_word_view(f),
            'result', jsonb_build_object('skipped', true, 'shown', w.shown));
    end if;
    return public.farm_state(f) || jsonb_build_object('word', public.farm_word_view(f));
end;
$$;

-- 7. Renaming a farm: 10,000 gold when the name changes (the farmer alone is free)
create or replace function public.farm_rename(p_name text, p_farmer text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_me uuid := auth.uid();
    f public.farms;
    v_name text := public.farm_clean_name(p_name);
    v_cost int := 0;
begin
    if v_me is null then raise exception 'not_authenticated'; end if;
    if p_farmer not in ('boy', 'girl') then raise exception 'bad_farmer'; end if;
    select * into f from public.farms where user_id = v_me for update;
    if not found then raise exception 'no_farm'; end if;
    if v_name is distinct from f.name then
        v_cost := 10000;
        if f.gold < v_cost then raise exception 'not_enough_gold'; end if;
    end if;
    update public.farms
       set name = v_name, farmer = p_farmer, gold = gold - v_cost, updated_at = now()
     where user_id = v_me
    returning * into f;
    return public.farm_state(f);
end;
$$;

-- 8. Who may call them
revoke all on function public.farm_word_view(public.farms) from public, anon, authenticated;
revoke all on function public.farm_word_get()               from public, anon;
revoke all on function public.farm_word_answer(text)        from public, anon;
revoke all on function public.farm_word_hint(text)          from public, anon;
grant execute on function public.farm_word_get()            to authenticated;
grant execute on function public.farm_word_answer(text)     to authenticated;
grant execute on function public.farm_word_hint(text)       to authenticated;
